language: python
install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
script:
  - pytest
jobs:
  include:
    - name: "Python 3.8 on Linux"
      python: 3.8           # this works for Linux but is ignored on macOS or Windows
    - name: "Python 3.8 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.8
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
